service: video-link-generator

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python2.7

functions:
  generateVideoLink:
    handler: handler.generateLink
    events:
      - http:
          path: generate-link
          method: post
